export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  DENTIST = 'DENTIST',
  HYGIENIST = 'HYGIENIST',
  ASSISTANT = 'ASSISTANT',
  RECEPTIONIST = 'RECEPTIONIST',
  ACCOUNTANT = 'ACCOUNTANT',
}
